### PR TITLE
Wagtail 50

### PR DESCRIPTION
**Pull request by nickmoreton**
## This updates the package for Wagtail 5.0 support.

Support ticket: https://torchbox.monday.com/boards/1124794299/pulses/1124795899

Dropped:

- python 3.7
- Django 4.0
- The documentation has been update to reflect the above.

Added tox github actions to run the tests.

### CODE REVIEW

**Review by katdom13 — APPROVED** [review]
This LGTM! Thanks

**Comment by seb-b** [comment]
I'm a bit confused how a support ticket was opened for an organisation we're not part of? Can I get some more context around this? There doesn't seem to be any actual code changes just tox and github actions (we don't use github actions internally)

**Comment by nickmoreton** [comment]
Hi @seb-b I added the actions because you have tests in place that can be run automatically.

The organisation is used internally here so other devs can work on your and many other packages without using our own accounts. It should help use keep track of the work we do on this and other packages (upgrades usually)

I've noted on out support board that this package is compatible with v5.0 and doesn't need a new release.

**Comment by seb-b** [comment]
good to know, thanks for the context.

**Pull request merged**
